[project]
name = "be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref==3.8.1",
    "cachetools==5.5.2",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "cryptography==44.0.1",
    "django==5.1.6",
    "django-cors-headers==4.7.0",
    "djangorestframework==3.15.2",
    "google-auth==2.28.0",
    "google-auth-httplib2==0.2.0",
    "google-auth-oauthlib==1.2.0",
    "gunicorn==23.0.0",
    "httplib2==0.31.0",
    "idna==3.10",
    "oauthlib==3.3.1",
    "packaging==25.0",
    "psycopg2-binary==2.9.11",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.2",
    "pycparser==2.22",
    "pyjwt==2.10.1",
    "pyparsing==3.2.5",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "requests-oauthlib==2.0.0",
    "rsa==4.9.1",
    "sqlparse==0.5.3",
    "urllib3==2.3.0",
    "waitress==3.0.2",
    "whitenoise==6.8.2",
]
