# Generated by Django 5.1.6 on 2025-03-10 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreApi', '0001_initial'),
        ('organizationApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizationApi.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='team_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizationApi.team'),
        ),
        migrations.AddField(
            model_name='order',
            name='tournament_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizationApi.tournament'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
