# Generated by Django 5.1.6 on 2025-03-10 13:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_status', models.BooleanField(default=True)),
                ('max_sets', models.PositiveSmallIntegerField(blank=True, default=3)),
                ('required_points', models.PositiveSmallIntegerField(blank=True, default=21)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_state', models.BooleanField(default=False)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('stage_number', models.IntegerField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoundRobinKnockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('scoring_type', models.CharField(choices=[('sets', 'Set-based scoring'), ('simple', 'Simple score')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixtureType', models.CharField(choices=[('KO', 'Knockout'), ('RR', 'Round Robin'), ('RR_KO', 'Round Robin + Knockout')], max_length=5)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_category', to='organizationApi.category')),
                ('fixture_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_fixture', to='organizationApi.fixture'),
        ),
        migrations.CreateModel(
            name='SimpleScore',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score_system', serialize=False, to='organizationApi.match')),
                ('team1_score', models.PositiveSmallIntegerField(default=0)),
                ('team2_score', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_category', to='organizationApi.category'),
        ),
        migrations.AddField(
            model_name='match',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='scheduled_matches',
            field=models.ManyToManyField(blank=True, related_name='scheduled_matches', to='organizationApi.match'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ph_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('mail', models.EmailField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoundRobin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(default=1)),
                ('all_matches', models.ManyToManyField(blank=True, related_name='rr_all_matches', to='organizationApi.match')),
                ('bracket_matches', models.ManyToManyField(blank=True, related_name='rr_match', to='organizationApi.match')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_category', to='organizationApi.category')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='organizationApi.sport'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organizationApi.category')),
            ],
        ),
        migrations.CreateModel(
            name='RR_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_rate', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('round_robin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_teams', to='organizationApi.roundrobin')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_team', to='organizationApi.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_team1', to='organizationApi.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_team2', to='organizationApi.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_winner', to='organizationApi.team'),
        ),
        migrations.CreateModel(
            name='Knockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_json', models.TextField(blank=True, db_column='json', null=True)),
                ('fixing_manual', models.BooleanField(default=False)),
                ('ko_stage', models.IntegerField(default=-1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='organizationApi.category')),
                ('all_matches', models.ManyToManyField(blank=True, related_name='bracket_all_matches', to='organizationApi.match')),
                ('bracket_matches', models.ManyToManyField(blank=True, related_name='bracket_match', to='organizationApi.match')),
                ('bracket_teams', models.ManyToManyField(blank=True, related_name='bracket', to='organizationApi.team')),
                ('winners_bracket', models.ManyToManyField(blank=True, related_name='bracket_winners', to='organizationApi.team')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_categories', to='organizationApi.team'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue_address', models.CharField(max_length=1024)),
                ('venue_link', models.URLField(blank=True, max_length=512, null=True)),
                ('ph_number', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizationApi.organization')),
                ('sport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizationApi.sport')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_court', to='organizationApi.match')),
                ('upcoming_matches', models.ManyToManyField(blank=True, related_name='upcoming_courts', to='organizationApi.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='organizationApi.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizationApi.tournament'),
        ),
        migrations.CreateModel(
            name='SetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('team1_points', models.PositiveSmallIntegerField(default=0)),
                ('team2_points', models.PositiveSmallIntegerField(default=0)),
                ('set_state', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='organizationApi.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_winner', to='organizationApi.team')),
            ],
            options={
                'unique_together': {('match', 'set_number')},
            },
        ),
    ]
