# Generated by Django 5.1.6 on 2025-11-14 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizationApi.sport'),
        ),
    ]
