# Generated by Django 5.1.6 on 2025-10-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrobinknockout',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rr_ko_category', to='organizationApi.category'),
        ),
        migrations.AddField(
            model_name='roundrobinknockout',
            name='knockout_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rr_ko_tournament', to='organizationApi.knockout'),
        ),
        migrations.AddField(
            model_name='roundrobinknockout',
            name='knockout_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roundrobinknockout',
            name='round_robin_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roundrobinknockout',
            name='round_robin_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rr_ko_tournament', to='organizationApi.roundrobin'),
        ),
    ]
